// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/prometheus.proto
// Protobuf Java Version: 4.27.1

package loghub.protobuf.prometheus;

public final class Prometheus {
  private Prometheus() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 1,
      /* suffix= */ "",
      Prometheus.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_loghub_protobuf_prometheus_WriteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_loghub_protobuf_prometheus_WriteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_loghub_protobuf_prometheus_TimeSeries_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_loghub_protobuf_prometheus_TimeSeries_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_loghub_protobuf_prometheus_Label_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_loghub_protobuf_prometheus_Label_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_loghub_protobuf_prometheus_Sample_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_loghub_protobuf_prometheus_Sample_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"src/main/protobuf/prometheus.proto\022\032lo" +
      "ghub.protobuf.prometheus\"V\n\014WriteRequest" +
      "\022:\n\ntimeseries\030\001 \003(\0132&.loghub.protobuf.p" +
      "rometheus.TimeSeriesJ\004\010\002\020\003J\004\010\003\020\004\"t\n\nTime" +
      "Series\0221\n\006labels\030\001 \003(\0132!.loghub.protobuf" +
      ".prometheus.Label\0223\n\007samples\030\002 \003(\0132\".log" +
      "hub.protobuf.prometheus.Sample\"$\n\005Label\022" +
      "\014\n\004name\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\"*\n\006Sample\022\r" +
      "\n\005value\030\001 \001(\001\022\021\n\ttimestamp\030\002 \001(\003B\002P\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_loghub_protobuf_prometheus_WriteRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_loghub_protobuf_prometheus_WriteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_loghub_protobuf_prometheus_WriteRequest_descriptor,
        new java.lang.String[] { "Timeseries", });
    internal_static_loghub_protobuf_prometheus_TimeSeries_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_loghub_protobuf_prometheus_TimeSeries_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_loghub_protobuf_prometheus_TimeSeries_descriptor,
        new java.lang.String[] { "Labels", "Samples", });
    internal_static_loghub_protobuf_prometheus_Label_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_loghub_protobuf_prometheus_Label_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_loghub_protobuf_prometheus_Label_descriptor,
        new java.lang.String[] { "Name", "Value", });
    internal_static_loghub_protobuf_prometheus_Sample_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_loghub_protobuf_prometheus_Sample_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_loghub_protobuf_prometheus_Sample_descriptor,
        new java.lang.String[] { "Value", "Timestamp", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
