// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/prometheus.proto
// Protobuf Java Version: 4.27.1

package loghub.protobuf.prometheus;

public interface SampleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:loghub.protobuf.prometheus.Sample)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double value = 1;</code>
   * @return The value.
   */
  double getValue();

  /**
   * <code>int64 timestamp = 2;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
