// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/prometheus.proto
// Protobuf Java Version: 4.27.1

package loghub.protobuf.prometheus;

public interface TimeSeriesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:loghub.protobuf.prometheus.TimeSeries)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .loghub.protobuf.prometheus.Label labels = 1;</code>
   */
  java.util.List<loghub.protobuf.prometheus.Label> 
      getLabelsList();
  /**
   * <code>repeated .loghub.protobuf.prometheus.Label labels = 1;</code>
   */
  loghub.protobuf.prometheus.Label getLabels(int index);
  /**
   * <code>repeated .loghub.protobuf.prometheus.Label labels = 1;</code>
   */
  int getLabelsCount();
  /**
   * <code>repeated .loghub.protobuf.prometheus.Label labels = 1;</code>
   */
  java.util.List<? extends loghub.protobuf.prometheus.LabelOrBuilder> 
      getLabelsOrBuilderList();
  /**
   * <code>repeated .loghub.protobuf.prometheus.Label labels = 1;</code>
   */
  loghub.protobuf.prometheus.LabelOrBuilder getLabelsOrBuilder(
      int index);

  /**
   * <code>repeated .loghub.protobuf.prometheus.Sample samples = 2;</code>
   */
  java.util.List<loghub.protobuf.prometheus.Sample> 
      getSamplesList();
  /**
   * <code>repeated .loghub.protobuf.prometheus.Sample samples = 2;</code>
   */
  loghub.protobuf.prometheus.Sample getSamples(int index);
  /**
   * <code>repeated .loghub.protobuf.prometheus.Sample samples = 2;</code>
   */
  int getSamplesCount();
  /**
   * <code>repeated .loghub.protobuf.prometheus.Sample samples = 2;</code>
   */
  java.util.List<? extends loghub.protobuf.prometheus.SampleOrBuilder> 
      getSamplesOrBuilderList();
  /**
   * <code>repeated .loghub.protobuf.prometheus.Sample samples = 2;</code>
   */
  loghub.protobuf.prometheus.SampleOrBuilder getSamplesOrBuilder(
      int index);
}
