// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/prometheus.proto
// Protobuf Java Version: 4.27.1

package loghub.protobuf.prometheus;

/**
 * Protobuf type {@code loghub.protobuf.prometheus.TimeSeries}
 */
public final class TimeSeries extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:loghub.protobuf.prometheus.TimeSeries)
    TimeSeriesOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 1,
      /* suffix= */ "",
      TimeSeries.class.getName());
  }
  // Use TimeSeries.newBuilder() to construct.
  private TimeSeries(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TimeSeries() {
    labels_ = java.util.Collections.emptyList();
    samples_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return loghub.protobuf.prometheus.Prometheus.internal_static_loghub_protobuf_prometheus_TimeSeries_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return loghub.protobuf.prometheus.Prometheus.internal_static_loghub_protobuf_prometheus_TimeSeries_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            loghub.protobuf.prometheus.TimeSeries.class, loghub.protobuf.prometheus.TimeSeries.Builder.class);
  }

  public static final int LABELS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<loghub.protobuf.prometheus.Label> labels_;
  /**
   * <code>repeated .loghub.protobuf.prometheus.Label labels = 1;</code>
   */
  @java.lang.Override
  public java.util.List<loghub.protobuf.prometheus.Label> getLabelsList() {
    return labels_;
  }
  /**
   * <code>repeated .loghub.protobuf.prometheus.Label labels = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends loghub.protobuf.prometheus.LabelOrBuilder> 
      getLabelsOrBuilderList() {
    return labels_;
  }
  /**
   * <code>repeated .loghub.protobuf.prometheus.Label labels = 1;</code>
   */
  @java.lang.Override
  public int getLabelsCount() {
    return labels_.size();
  }
  /**
   * <code>repeated .loghub.protobuf.prometheus.Label labels = 1;</code>
   */
  @java.lang.Override
  public loghub.protobuf.prometheus.Label getLabels(int index) {
    return labels_.get(index);
  }
  /**
   * <code>repeated .loghub.protobuf.prometheus.Label labels = 1;</code>
   */
  @java.lang.Override
  public loghub.protobuf.prometheus.LabelOrBuilder getLabelsOrBuilder(
      int index) {
    return labels_.get(index);
  }

  public static final int SAMPLES_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<loghub.protobuf.prometheus.Sample> samples_;
  /**
   * <code>repeated .loghub.protobuf.prometheus.Sample samples = 2;</code>
   */
  @java.lang.Override
  public java.util.List<loghub.protobuf.prometheus.Sample> getSamplesList() {
    return samples_;
  }
  /**
   * <code>repeated .loghub.protobuf.prometheus.Sample samples = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends loghub.protobuf.prometheus.SampleOrBuilder> 
      getSamplesOrBuilderList() {
    return samples_;
  }
  /**
   * <code>repeated .loghub.protobuf.prometheus.Sample samples = 2;</code>
   */
  @java.lang.Override
  public int getSamplesCount() {
    return samples_.size();
  }
  /**
   * <code>repeated .loghub.protobuf.prometheus.Sample samples = 2;</code>
   */
  @java.lang.Override
  public loghub.protobuf.prometheus.Sample getSamples(int index) {
    return samples_.get(index);
  }
  /**
   * <code>repeated .loghub.protobuf.prometheus.Sample samples = 2;</code>
   */
  @java.lang.Override
  public loghub.protobuf.prometheus.SampleOrBuilder getSamplesOrBuilder(
      int index) {
    return samples_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < labels_.size(); i++) {
      output.writeMessage(1, labels_.get(i));
    }
    for (int i = 0; i < samples_.size(); i++) {
      output.writeMessage(2, samples_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < labels_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, labels_.get(i));
    }
    for (int i = 0; i < samples_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, samples_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof loghub.protobuf.prometheus.TimeSeries)) {
      return super.equals(obj);
    }
    loghub.protobuf.prometheus.TimeSeries other = (loghub.protobuf.prometheus.TimeSeries) obj;

    if (!getLabelsList()
        .equals(other.getLabelsList())) return false;
    if (!getSamplesList()
        .equals(other.getSamplesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getLabelsCount() > 0) {
      hash = (37 * hash) + LABELS_FIELD_NUMBER;
      hash = (53 * hash) + getLabelsList().hashCode();
    }
    if (getSamplesCount() > 0) {
      hash = (37 * hash) + SAMPLES_FIELD_NUMBER;
      hash = (53 * hash) + getSamplesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static loghub.protobuf.prometheus.TimeSeries parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static loghub.protobuf.prometheus.TimeSeries parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static loghub.protobuf.prometheus.TimeSeries parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static loghub.protobuf.prometheus.TimeSeries parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static loghub.protobuf.prometheus.TimeSeries parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static loghub.protobuf.prometheus.TimeSeries parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static loghub.protobuf.prometheus.TimeSeries parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static loghub.protobuf.prometheus.TimeSeries parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static loghub.protobuf.prometheus.TimeSeries parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static loghub.protobuf.prometheus.TimeSeries parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static loghub.protobuf.prometheus.TimeSeries parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static loghub.protobuf.prometheus.TimeSeries parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(loghub.protobuf.prometheus.TimeSeries prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code loghub.protobuf.prometheus.TimeSeries}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:loghub.protobuf.prometheus.TimeSeries)
      loghub.protobuf.prometheus.TimeSeriesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return loghub.protobuf.prometheus.Prometheus.internal_static_loghub_protobuf_prometheus_TimeSeries_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return loghub.protobuf.prometheus.Prometheus.internal_static_loghub_protobuf_prometheus_TimeSeries_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              loghub.protobuf.prometheus.TimeSeries.class, loghub.protobuf.prometheus.TimeSeries.Builder.class);
    }

    // Construct using loghub.protobuf.prometheus.TimeSeries.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (labelsBuilder_ == null) {
        labels_ = java.util.Collections.emptyList();
      } else {
        labels_ = null;
        labelsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (samplesBuilder_ == null) {
        samples_ = java.util.Collections.emptyList();
      } else {
        samples_ = null;
        samplesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return loghub.protobuf.prometheus.Prometheus.internal_static_loghub_protobuf_prometheus_TimeSeries_descriptor;
    }

    @java.lang.Override
    public loghub.protobuf.prometheus.TimeSeries getDefaultInstanceForType() {
      return loghub.protobuf.prometheus.TimeSeries.getDefaultInstance();
    }

    @java.lang.Override
    public loghub.protobuf.prometheus.TimeSeries build() {
      loghub.protobuf.prometheus.TimeSeries result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public loghub.protobuf.prometheus.TimeSeries buildPartial() {
      loghub.protobuf.prometheus.TimeSeries result = new loghub.protobuf.prometheus.TimeSeries(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(loghub.protobuf.prometheus.TimeSeries result) {
      if (labelsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          labels_ = java.util.Collections.unmodifiableList(labels_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.labels_ = labels_;
      } else {
        result.labels_ = labelsBuilder_.build();
      }
      if (samplesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          samples_ = java.util.Collections.unmodifiableList(samples_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.samples_ = samples_;
      } else {
        result.samples_ = samplesBuilder_.build();
      }
    }

    private void buildPartial0(loghub.protobuf.prometheus.TimeSeries result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof loghub.protobuf.prometheus.TimeSeries) {
        return mergeFrom((loghub.protobuf.prometheus.TimeSeries)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(loghub.protobuf.prometheus.TimeSeries other) {
      if (other == loghub.protobuf.prometheus.TimeSeries.getDefaultInstance()) return this;
      if (labelsBuilder_ == null) {
        if (!other.labels_.isEmpty()) {
          if (labels_.isEmpty()) {
            labels_ = other.labels_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureLabelsIsMutable();
            labels_.addAll(other.labels_);
          }
          onChanged();
        }
      } else {
        if (!other.labels_.isEmpty()) {
          if (labelsBuilder_.isEmpty()) {
            labelsBuilder_.dispose();
            labelsBuilder_ = null;
            labels_ = other.labels_;
            bitField0_ = (bitField0_ & ~0x00000001);
            labelsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getLabelsFieldBuilder() : null;
          } else {
            labelsBuilder_.addAllMessages(other.labels_);
          }
        }
      }
      if (samplesBuilder_ == null) {
        if (!other.samples_.isEmpty()) {
          if (samples_.isEmpty()) {
            samples_ = other.samples_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureSamplesIsMutable();
            samples_.addAll(other.samples_);
          }
          onChanged();
        }
      } else {
        if (!other.samples_.isEmpty()) {
          if (samplesBuilder_.isEmpty()) {
            samplesBuilder_.dispose();
            samplesBuilder_ = null;
            samples_ = other.samples_;
            bitField0_ = (bitField0_ & ~0x00000002);
            samplesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getSamplesFieldBuilder() : null;
          } else {
            samplesBuilder_.addAllMessages(other.samples_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              loghub.protobuf.prometheus.Label m =
                  input.readMessage(
                      loghub.protobuf.prometheus.Label.parser(),
                      extensionRegistry);
              if (labelsBuilder_ == null) {
                ensureLabelsIsMutable();
                labels_.add(m);
              } else {
                labelsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              loghub.protobuf.prometheus.Sample m =
                  input.readMessage(
                      loghub.protobuf.prometheus.Sample.parser(),
                      extensionRegistry);
              if (samplesBuilder_ == null) {
                ensureSamplesIsMutable();
                samples_.add(m);
              } else {
                samplesBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<loghub.protobuf.prometheus.Label> labels_ =
      java.util.Collections.emptyList();
    private void ensureLabelsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        labels_ = new java.util.ArrayList<loghub.protobuf.prometheus.Label>(labels_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        loghub.protobuf.prometheus.Label, loghub.protobuf.prometheus.Label.Builder, loghub.protobuf.prometheus.LabelOrBuilder> labelsBuilder_;

    /**
     * <code>repeated .loghub.protobuf.prometheus.Label labels = 1;</code>
     */
    public java.util.List<loghub.protobuf.prometheus.Label> getLabelsList() {
      if (labelsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(labels_);
      } else {
        return labelsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Label labels = 1;</code>
     */
    public int getLabelsCount() {
      if (labelsBuilder_ == null) {
        return labels_.size();
      } else {
        return labelsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Label labels = 1;</code>
     */
    public loghub.protobuf.prometheus.Label getLabels(int index) {
      if (labelsBuilder_ == null) {
        return labels_.get(index);
      } else {
        return labelsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Label labels = 1;</code>
     */
    public Builder setLabels(
        int index, loghub.protobuf.prometheus.Label value) {
      if (labelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLabelsIsMutable();
        labels_.set(index, value);
        onChanged();
      } else {
        labelsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Label labels = 1;</code>
     */
    public Builder setLabels(
        int index, loghub.protobuf.prometheus.Label.Builder builderForValue) {
      if (labelsBuilder_ == null) {
        ensureLabelsIsMutable();
        labels_.set(index, builderForValue.build());
        onChanged();
      } else {
        labelsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Label labels = 1;</code>
     */
    public Builder addLabels(loghub.protobuf.prometheus.Label value) {
      if (labelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLabelsIsMutable();
        labels_.add(value);
        onChanged();
      } else {
        labelsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Label labels = 1;</code>
     */
    public Builder addLabels(
        int index, loghub.protobuf.prometheus.Label value) {
      if (labelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLabelsIsMutable();
        labels_.add(index, value);
        onChanged();
      } else {
        labelsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Label labels = 1;</code>
     */
    public Builder addLabels(
        loghub.protobuf.prometheus.Label.Builder builderForValue) {
      if (labelsBuilder_ == null) {
        ensureLabelsIsMutable();
        labels_.add(builderForValue.build());
        onChanged();
      } else {
        labelsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Label labels = 1;</code>
     */
    public Builder addLabels(
        int index, loghub.protobuf.prometheus.Label.Builder builderForValue) {
      if (labelsBuilder_ == null) {
        ensureLabelsIsMutable();
        labels_.add(index, builderForValue.build());
        onChanged();
      } else {
        labelsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Label labels = 1;</code>
     */
    public Builder addAllLabels(
        java.lang.Iterable<? extends loghub.protobuf.prometheus.Label> values) {
      if (labelsBuilder_ == null) {
        ensureLabelsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, labels_);
        onChanged();
      } else {
        labelsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Label labels = 1;</code>
     */
    public Builder clearLabels() {
      if (labelsBuilder_ == null) {
        labels_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        labelsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Label labels = 1;</code>
     */
    public Builder removeLabels(int index) {
      if (labelsBuilder_ == null) {
        ensureLabelsIsMutable();
        labels_.remove(index);
        onChanged();
      } else {
        labelsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Label labels = 1;</code>
     */
    public loghub.protobuf.prometheus.Label.Builder getLabelsBuilder(
        int index) {
      return getLabelsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Label labels = 1;</code>
     */
    public loghub.protobuf.prometheus.LabelOrBuilder getLabelsOrBuilder(
        int index) {
      if (labelsBuilder_ == null) {
        return labels_.get(index);  } else {
        return labelsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Label labels = 1;</code>
     */
    public java.util.List<? extends loghub.protobuf.prometheus.LabelOrBuilder> 
         getLabelsOrBuilderList() {
      if (labelsBuilder_ != null) {
        return labelsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(labels_);
      }
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Label labels = 1;</code>
     */
    public loghub.protobuf.prometheus.Label.Builder addLabelsBuilder() {
      return getLabelsFieldBuilder().addBuilder(
          loghub.protobuf.prometheus.Label.getDefaultInstance());
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Label labels = 1;</code>
     */
    public loghub.protobuf.prometheus.Label.Builder addLabelsBuilder(
        int index) {
      return getLabelsFieldBuilder().addBuilder(
          index, loghub.protobuf.prometheus.Label.getDefaultInstance());
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Label labels = 1;</code>
     */
    public java.util.List<loghub.protobuf.prometheus.Label.Builder> 
         getLabelsBuilderList() {
      return getLabelsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        loghub.protobuf.prometheus.Label, loghub.protobuf.prometheus.Label.Builder, loghub.protobuf.prometheus.LabelOrBuilder> 
        getLabelsFieldBuilder() {
      if (labelsBuilder_ == null) {
        labelsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            loghub.protobuf.prometheus.Label, loghub.protobuf.prometheus.Label.Builder, loghub.protobuf.prometheus.LabelOrBuilder>(
                labels_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        labels_ = null;
      }
      return labelsBuilder_;
    }

    private java.util.List<loghub.protobuf.prometheus.Sample> samples_ =
      java.util.Collections.emptyList();
    private void ensureSamplesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        samples_ = new java.util.ArrayList<loghub.protobuf.prometheus.Sample>(samples_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        loghub.protobuf.prometheus.Sample, loghub.protobuf.prometheus.Sample.Builder, loghub.protobuf.prometheus.SampleOrBuilder> samplesBuilder_;

    /**
     * <code>repeated .loghub.protobuf.prometheus.Sample samples = 2;</code>
     */
    public java.util.List<loghub.protobuf.prometheus.Sample> getSamplesList() {
      if (samplesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(samples_);
      } else {
        return samplesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Sample samples = 2;</code>
     */
    public int getSamplesCount() {
      if (samplesBuilder_ == null) {
        return samples_.size();
      } else {
        return samplesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Sample samples = 2;</code>
     */
    public loghub.protobuf.prometheus.Sample getSamples(int index) {
      if (samplesBuilder_ == null) {
        return samples_.get(index);
      } else {
        return samplesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Sample samples = 2;</code>
     */
    public Builder setSamples(
        int index, loghub.protobuf.prometheus.Sample value) {
      if (samplesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSamplesIsMutable();
        samples_.set(index, value);
        onChanged();
      } else {
        samplesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Sample samples = 2;</code>
     */
    public Builder setSamples(
        int index, loghub.protobuf.prometheus.Sample.Builder builderForValue) {
      if (samplesBuilder_ == null) {
        ensureSamplesIsMutable();
        samples_.set(index, builderForValue.build());
        onChanged();
      } else {
        samplesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Sample samples = 2;</code>
     */
    public Builder addSamples(loghub.protobuf.prometheus.Sample value) {
      if (samplesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSamplesIsMutable();
        samples_.add(value);
        onChanged();
      } else {
        samplesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Sample samples = 2;</code>
     */
    public Builder addSamples(
        int index, loghub.protobuf.prometheus.Sample value) {
      if (samplesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSamplesIsMutable();
        samples_.add(index, value);
        onChanged();
      } else {
        samplesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Sample samples = 2;</code>
     */
    public Builder addSamples(
        loghub.protobuf.prometheus.Sample.Builder builderForValue) {
      if (samplesBuilder_ == null) {
        ensureSamplesIsMutable();
        samples_.add(builderForValue.build());
        onChanged();
      } else {
        samplesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Sample samples = 2;</code>
     */
    public Builder addSamples(
        int index, loghub.protobuf.prometheus.Sample.Builder builderForValue) {
      if (samplesBuilder_ == null) {
        ensureSamplesIsMutable();
        samples_.add(index, builderForValue.build());
        onChanged();
      } else {
        samplesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Sample samples = 2;</code>
     */
    public Builder addAllSamples(
        java.lang.Iterable<? extends loghub.protobuf.prometheus.Sample> values) {
      if (samplesBuilder_ == null) {
        ensureSamplesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, samples_);
        onChanged();
      } else {
        samplesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Sample samples = 2;</code>
     */
    public Builder clearSamples() {
      if (samplesBuilder_ == null) {
        samples_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        samplesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Sample samples = 2;</code>
     */
    public Builder removeSamples(int index) {
      if (samplesBuilder_ == null) {
        ensureSamplesIsMutable();
        samples_.remove(index);
        onChanged();
      } else {
        samplesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Sample samples = 2;</code>
     */
    public loghub.protobuf.prometheus.Sample.Builder getSamplesBuilder(
        int index) {
      return getSamplesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Sample samples = 2;</code>
     */
    public loghub.protobuf.prometheus.SampleOrBuilder getSamplesOrBuilder(
        int index) {
      if (samplesBuilder_ == null) {
        return samples_.get(index);  } else {
        return samplesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Sample samples = 2;</code>
     */
    public java.util.List<? extends loghub.protobuf.prometheus.SampleOrBuilder> 
         getSamplesOrBuilderList() {
      if (samplesBuilder_ != null) {
        return samplesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(samples_);
      }
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Sample samples = 2;</code>
     */
    public loghub.protobuf.prometheus.Sample.Builder addSamplesBuilder() {
      return getSamplesFieldBuilder().addBuilder(
          loghub.protobuf.prometheus.Sample.getDefaultInstance());
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Sample samples = 2;</code>
     */
    public loghub.protobuf.prometheus.Sample.Builder addSamplesBuilder(
        int index) {
      return getSamplesFieldBuilder().addBuilder(
          index, loghub.protobuf.prometheus.Sample.getDefaultInstance());
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.Sample samples = 2;</code>
     */
    public java.util.List<loghub.protobuf.prometheus.Sample.Builder> 
         getSamplesBuilderList() {
      return getSamplesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        loghub.protobuf.prometheus.Sample, loghub.protobuf.prometheus.Sample.Builder, loghub.protobuf.prometheus.SampleOrBuilder> 
        getSamplesFieldBuilder() {
      if (samplesBuilder_ == null) {
        samplesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            loghub.protobuf.prometheus.Sample, loghub.protobuf.prometheus.Sample.Builder, loghub.protobuf.prometheus.SampleOrBuilder>(
                samples_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        samples_ = null;
      }
      return samplesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:loghub.protobuf.prometheus.TimeSeries)
  }

  // @@protoc_insertion_point(class_scope:loghub.protobuf.prometheus.TimeSeries)
  private static final loghub.protobuf.prometheus.TimeSeries DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new loghub.protobuf.prometheus.TimeSeries();
  }

  public static loghub.protobuf.prometheus.TimeSeries getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TimeSeries>
      PARSER = new com.google.protobuf.AbstractParser<TimeSeries>() {
    @java.lang.Override
    public TimeSeries parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TimeSeries> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TimeSeries> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public loghub.protobuf.prometheus.TimeSeries getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

