// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/prometheus.proto
// Protobuf Java Version: 4.27.1

package loghub.protobuf.prometheus;

public interface WriteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:loghub.protobuf.prometheus.WriteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .loghub.protobuf.prometheus.TimeSeries timeseries = 1;</code>
   */
  java.util.List<loghub.protobuf.prometheus.TimeSeries> 
      getTimeseriesList();
  /**
   * <code>repeated .loghub.protobuf.prometheus.TimeSeries timeseries = 1;</code>
   */
  loghub.protobuf.prometheus.TimeSeries getTimeseries(int index);
  /**
   * <code>repeated .loghub.protobuf.prometheus.TimeSeries timeseries = 1;</code>
   */
  int getTimeseriesCount();
  /**
   * <code>repeated .loghub.protobuf.prometheus.TimeSeries timeseries = 1;</code>
   */
  java.util.List<? extends loghub.protobuf.prometheus.TimeSeriesOrBuilder> 
      getTimeseriesOrBuilderList();
  /**
   * <code>repeated .loghub.protobuf.prometheus.TimeSeries timeseries = 1;</code>
   */
  loghub.protobuf.prometheus.TimeSeriesOrBuilder getTimeseriesOrBuilder(
      int index);
}
