// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/prometheus.proto
// Protobuf Java Version: 4.27.1

package loghub.protobuf.prometheus;

/**
 * Protobuf type {@code loghub.protobuf.prometheus.WriteRequest}
 */
public final class WriteRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:loghub.protobuf.prometheus.WriteRequest)
    WriteRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 1,
      /* suffix= */ "",
      WriteRequest.class.getName());
  }
  // Use WriteRequest.newBuilder() to construct.
  private WriteRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private WriteRequest() {
    timeseries_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return loghub.protobuf.prometheus.Prometheus.internal_static_loghub_protobuf_prometheus_WriteRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return loghub.protobuf.prometheus.Prometheus.internal_static_loghub_protobuf_prometheus_WriteRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            loghub.protobuf.prometheus.WriteRequest.class, loghub.protobuf.prometheus.WriteRequest.Builder.class);
  }

  public static final int TIMESERIES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<loghub.protobuf.prometheus.TimeSeries> timeseries_;
  /**
   * <code>repeated .loghub.protobuf.prometheus.TimeSeries timeseries = 1;</code>
   */
  @java.lang.Override
  public java.util.List<loghub.protobuf.prometheus.TimeSeries> getTimeseriesList() {
    return timeseries_;
  }
  /**
   * <code>repeated .loghub.protobuf.prometheus.TimeSeries timeseries = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends loghub.protobuf.prometheus.TimeSeriesOrBuilder> 
      getTimeseriesOrBuilderList() {
    return timeseries_;
  }
  /**
   * <code>repeated .loghub.protobuf.prometheus.TimeSeries timeseries = 1;</code>
   */
  @java.lang.Override
  public int getTimeseriesCount() {
    return timeseries_.size();
  }
  /**
   * <code>repeated .loghub.protobuf.prometheus.TimeSeries timeseries = 1;</code>
   */
  @java.lang.Override
  public loghub.protobuf.prometheus.TimeSeries getTimeseries(int index) {
    return timeseries_.get(index);
  }
  /**
   * <code>repeated .loghub.protobuf.prometheus.TimeSeries timeseries = 1;</code>
   */
  @java.lang.Override
  public loghub.protobuf.prometheus.TimeSeriesOrBuilder getTimeseriesOrBuilder(
      int index) {
    return timeseries_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < timeseries_.size(); i++) {
      output.writeMessage(1, timeseries_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < timeseries_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, timeseries_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof loghub.protobuf.prometheus.WriteRequest)) {
      return super.equals(obj);
    }
    loghub.protobuf.prometheus.WriteRequest other = (loghub.protobuf.prometheus.WriteRequest) obj;

    if (!getTimeseriesList()
        .equals(other.getTimeseriesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTimeseriesCount() > 0) {
      hash = (37 * hash) + TIMESERIES_FIELD_NUMBER;
      hash = (53 * hash) + getTimeseriesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static loghub.protobuf.prometheus.WriteRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static loghub.protobuf.prometheus.WriteRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static loghub.protobuf.prometheus.WriteRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static loghub.protobuf.prometheus.WriteRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static loghub.protobuf.prometheus.WriteRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static loghub.protobuf.prometheus.WriteRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static loghub.protobuf.prometheus.WriteRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static loghub.protobuf.prometheus.WriteRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static loghub.protobuf.prometheus.WriteRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static loghub.protobuf.prometheus.WriteRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static loghub.protobuf.prometheus.WriteRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static loghub.protobuf.prometheus.WriteRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(loghub.protobuf.prometheus.WriteRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code loghub.protobuf.prometheus.WriteRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:loghub.protobuf.prometheus.WriteRequest)
      loghub.protobuf.prometheus.WriteRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return loghub.protobuf.prometheus.Prometheus.internal_static_loghub_protobuf_prometheus_WriteRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return loghub.protobuf.prometheus.Prometheus.internal_static_loghub_protobuf_prometheus_WriteRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              loghub.protobuf.prometheus.WriteRequest.class, loghub.protobuf.prometheus.WriteRequest.Builder.class);
    }

    // Construct using loghub.protobuf.prometheus.WriteRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (timeseriesBuilder_ == null) {
        timeseries_ = java.util.Collections.emptyList();
      } else {
        timeseries_ = null;
        timeseriesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return loghub.protobuf.prometheus.Prometheus.internal_static_loghub_protobuf_prometheus_WriteRequest_descriptor;
    }

    @java.lang.Override
    public loghub.protobuf.prometheus.WriteRequest getDefaultInstanceForType() {
      return loghub.protobuf.prometheus.WriteRequest.getDefaultInstance();
    }

    @java.lang.Override
    public loghub.protobuf.prometheus.WriteRequest build() {
      loghub.protobuf.prometheus.WriteRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public loghub.protobuf.prometheus.WriteRequest buildPartial() {
      loghub.protobuf.prometheus.WriteRequest result = new loghub.protobuf.prometheus.WriteRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(loghub.protobuf.prometheus.WriteRequest result) {
      if (timeseriesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          timeseries_ = java.util.Collections.unmodifiableList(timeseries_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.timeseries_ = timeseries_;
      } else {
        result.timeseries_ = timeseriesBuilder_.build();
      }
    }

    private void buildPartial0(loghub.protobuf.prometheus.WriteRequest result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof loghub.protobuf.prometheus.WriteRequest) {
        return mergeFrom((loghub.protobuf.prometheus.WriteRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(loghub.protobuf.prometheus.WriteRequest other) {
      if (other == loghub.protobuf.prometheus.WriteRequest.getDefaultInstance()) return this;
      if (timeseriesBuilder_ == null) {
        if (!other.timeseries_.isEmpty()) {
          if (timeseries_.isEmpty()) {
            timeseries_ = other.timeseries_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTimeseriesIsMutable();
            timeseries_.addAll(other.timeseries_);
          }
          onChanged();
        }
      } else {
        if (!other.timeseries_.isEmpty()) {
          if (timeseriesBuilder_.isEmpty()) {
            timeseriesBuilder_.dispose();
            timeseriesBuilder_ = null;
            timeseries_ = other.timeseries_;
            bitField0_ = (bitField0_ & ~0x00000001);
            timeseriesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getTimeseriesFieldBuilder() : null;
          } else {
            timeseriesBuilder_.addAllMessages(other.timeseries_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              loghub.protobuf.prometheus.TimeSeries m =
                  input.readMessage(
                      loghub.protobuf.prometheus.TimeSeries.parser(),
                      extensionRegistry);
              if (timeseriesBuilder_ == null) {
                ensureTimeseriesIsMutable();
                timeseries_.add(m);
              } else {
                timeseriesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<loghub.protobuf.prometheus.TimeSeries> timeseries_ =
      java.util.Collections.emptyList();
    private void ensureTimeseriesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        timeseries_ = new java.util.ArrayList<loghub.protobuf.prometheus.TimeSeries>(timeseries_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        loghub.protobuf.prometheus.TimeSeries, loghub.protobuf.prometheus.TimeSeries.Builder, loghub.protobuf.prometheus.TimeSeriesOrBuilder> timeseriesBuilder_;

    /**
     * <code>repeated .loghub.protobuf.prometheus.TimeSeries timeseries = 1;</code>
     */
    public java.util.List<loghub.protobuf.prometheus.TimeSeries> getTimeseriesList() {
      if (timeseriesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(timeseries_);
      } else {
        return timeseriesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.TimeSeries timeseries = 1;</code>
     */
    public int getTimeseriesCount() {
      if (timeseriesBuilder_ == null) {
        return timeseries_.size();
      } else {
        return timeseriesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.TimeSeries timeseries = 1;</code>
     */
    public loghub.protobuf.prometheus.TimeSeries getTimeseries(int index) {
      if (timeseriesBuilder_ == null) {
        return timeseries_.get(index);
      } else {
        return timeseriesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.TimeSeries timeseries = 1;</code>
     */
    public Builder setTimeseries(
        int index, loghub.protobuf.prometheus.TimeSeries value) {
      if (timeseriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTimeseriesIsMutable();
        timeseries_.set(index, value);
        onChanged();
      } else {
        timeseriesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.TimeSeries timeseries = 1;</code>
     */
    public Builder setTimeseries(
        int index, loghub.protobuf.prometheus.TimeSeries.Builder builderForValue) {
      if (timeseriesBuilder_ == null) {
        ensureTimeseriesIsMutable();
        timeseries_.set(index, builderForValue.build());
        onChanged();
      } else {
        timeseriesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.TimeSeries timeseries = 1;</code>
     */
    public Builder addTimeseries(loghub.protobuf.prometheus.TimeSeries value) {
      if (timeseriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTimeseriesIsMutable();
        timeseries_.add(value);
        onChanged();
      } else {
        timeseriesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.TimeSeries timeseries = 1;</code>
     */
    public Builder addTimeseries(
        int index, loghub.protobuf.prometheus.TimeSeries value) {
      if (timeseriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTimeseriesIsMutable();
        timeseries_.add(index, value);
        onChanged();
      } else {
        timeseriesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.TimeSeries timeseries = 1;</code>
     */
    public Builder addTimeseries(
        loghub.protobuf.prometheus.TimeSeries.Builder builderForValue) {
      if (timeseriesBuilder_ == null) {
        ensureTimeseriesIsMutable();
        timeseries_.add(builderForValue.build());
        onChanged();
      } else {
        timeseriesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.TimeSeries timeseries = 1;</code>
     */
    public Builder addTimeseries(
        int index, loghub.protobuf.prometheus.TimeSeries.Builder builderForValue) {
      if (timeseriesBuilder_ == null) {
        ensureTimeseriesIsMutable();
        timeseries_.add(index, builderForValue.build());
        onChanged();
      } else {
        timeseriesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.TimeSeries timeseries = 1;</code>
     */
    public Builder addAllTimeseries(
        java.lang.Iterable<? extends loghub.protobuf.prometheus.TimeSeries> values) {
      if (timeseriesBuilder_ == null) {
        ensureTimeseriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, timeseries_);
        onChanged();
      } else {
        timeseriesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.TimeSeries timeseries = 1;</code>
     */
    public Builder clearTimeseries() {
      if (timeseriesBuilder_ == null) {
        timeseries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        timeseriesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.TimeSeries timeseries = 1;</code>
     */
    public Builder removeTimeseries(int index) {
      if (timeseriesBuilder_ == null) {
        ensureTimeseriesIsMutable();
        timeseries_.remove(index);
        onChanged();
      } else {
        timeseriesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.TimeSeries timeseries = 1;</code>
     */
    public loghub.protobuf.prometheus.TimeSeries.Builder getTimeseriesBuilder(
        int index) {
      return getTimeseriesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.TimeSeries timeseries = 1;</code>
     */
    public loghub.protobuf.prometheus.TimeSeriesOrBuilder getTimeseriesOrBuilder(
        int index) {
      if (timeseriesBuilder_ == null) {
        return timeseries_.get(index);  } else {
        return timeseriesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.TimeSeries timeseries = 1;</code>
     */
    public java.util.List<? extends loghub.protobuf.prometheus.TimeSeriesOrBuilder> 
         getTimeseriesOrBuilderList() {
      if (timeseriesBuilder_ != null) {
        return timeseriesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(timeseries_);
      }
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.TimeSeries timeseries = 1;</code>
     */
    public loghub.protobuf.prometheus.TimeSeries.Builder addTimeseriesBuilder() {
      return getTimeseriesFieldBuilder().addBuilder(
          loghub.protobuf.prometheus.TimeSeries.getDefaultInstance());
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.TimeSeries timeseries = 1;</code>
     */
    public loghub.protobuf.prometheus.TimeSeries.Builder addTimeseriesBuilder(
        int index) {
      return getTimeseriesFieldBuilder().addBuilder(
          index, loghub.protobuf.prometheus.TimeSeries.getDefaultInstance());
    }
    /**
     * <code>repeated .loghub.protobuf.prometheus.TimeSeries timeseries = 1;</code>
     */
    public java.util.List<loghub.protobuf.prometheus.TimeSeries.Builder> 
         getTimeseriesBuilderList() {
      return getTimeseriesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        loghub.protobuf.prometheus.TimeSeries, loghub.protobuf.prometheus.TimeSeries.Builder, loghub.protobuf.prometheus.TimeSeriesOrBuilder> 
        getTimeseriesFieldBuilder() {
      if (timeseriesBuilder_ == null) {
        timeseriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            loghub.protobuf.prometheus.TimeSeries, loghub.protobuf.prometheus.TimeSeries.Builder, loghub.protobuf.prometheus.TimeSeriesOrBuilder>(
                timeseries_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        timeseries_ = null;
      }
      return timeseriesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:loghub.protobuf.prometheus.WriteRequest)
  }

  // @@protoc_insertion_point(class_scope:loghub.protobuf.prometheus.WriteRequest)
  private static final loghub.protobuf.prometheus.WriteRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new loghub.protobuf.prometheus.WriteRequest();
  }

  public static loghub.protobuf.prometheus.WriteRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WriteRequest>
      PARSER = new com.google.protobuf.AbstractParser<WriteRequest>() {
    @java.lang.Override
    public WriteRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<WriteRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WriteRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public loghub.protobuf.prometheus.WriteRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

